
VARIABLE NUMBERS 2048 CELLS ALLOT
VARIABLE NUMBER-COUNT
VARIABLE PREV
VARIABLE ANSWER

S" MAX-N" ENVIRONMENT? DROP CONSTANT MAX-N

: NTH ( index -- addr)
  NUMBERS SWAP CELLS +
;

: READ-INPUT
  BEGIN
    PAD 80 STDIN READ-LINE THROW
  WHILE
    0 0 ROT PAD SWAP >NUMBER DROP DROP D>S
    NUMBER-COUNT @ NTH !
    1 NUMBER-COUNT +!
  REPEAT DROP ;

: COMP-AND-INC ( current-sum --)
  DUP
  PREV @ > NEGATE ANSWER +!
  PREV !
;

: INIT MAX-N PREV ! 0 ANSWER ! ;
: DISPLAY ANSWER @ . CR ;

: PART1 ( --)
  INIT
  NUMBER-COUNT @ 0 DO
    I NTH @
    COMP-AND-INC
  LOOP DISPLAY
;

: PART2 ( --)
  INIT
  NUMBER-COUNT @ 2 - 0 DO
    I 0 + NTH @
    I 1 + NTH @
    I 2 + NTH @
    + +
    COMP-AND-INC
  LOOP DISPLAY
;

READ-INPUT PART1 PART2 QUIT
