VARIABLE NUMBERS 2048 CELLS ALLOT
VARIABLE NUMBER-COUNT
VARIABLE WINDOW
VARIABLE ANSWER1

S" MAX-N" ENVIRONMENT? DROP WINDOW !

: NTH ( index -- addr)
  NUMBERS SWAP CELLS +
;

: READ-INPUT
  BEGIN
    PAD 80 STDIN READ-LINE THROW
  WHILE
    0 0 ROT PAD SWAP >NUMBER DROP DROP D>S
    NUMBER-COUNT @ NTH !
    1 NUMBER-COUNT +!
  REPEAT DROP ;


: PART1
  NUMBER-COUNT @ 2 - 0 DO
    I 0 + NTH @
    I 1 + NTH @
    I 2 + NTH @
    + + DUP
    WINDOW @ > NEGATE ANSWER1 +!
    WINDOW !
  LOOP ANSWER1 @ . CR ;

READ-INPUT PART1 QUIT
