
16384 CONSTANT INPUT-CAP
CREATE INPUT INPUT-CAP ALLOT
VARIABLE INPUT-SIZE

INPUT INPUT-CAP STDIN READ-FILE THROW
INPUT-SIZE !

VARIABLE X
VARIABLE Y

: -! SWAP NEGATE SWAP +! ;
: LOOKAHEAD PARSE-NAME EVALUATE ;

: PRINT-ANSWER
  0 X !
  0 Y !
  INPUT INPUT-SIZE @ EVALUATE
  X @ Y @ * . CR
;

\ PART 1
: FORWARD LOOKAHEAD X +! ;
: DOWN    LOOKAHEAD Y +! ;
: UP      LOOKAHEAD Y -! ;
PRINT-ANSWER

\ PART 2
WARNINGS OFF \ SUPPRESS REDEFINED MESSAGES
VARIABLE AIM
: DOWN LOOKAHEAD AIM +! ;
: UP   LOOKAHEAD AIM -! ;
: FORWARD
  LOOKAHEAD DUP
  X +!
  AIM @ * Y +!
;
PRINT-ANSWER

QUIT
