

16384 CONSTANT INPUT-CAP
CREATE INPUT INPUT-CAP ALLOT
VARIABLE INPUT-SIZE

INPUT INPUT-CAP STDIN READ-FILE THROW
INPUT-SIZE !

VARIABLE X
VARIABLE Y

: -! SWAP NEGATE SWAP +! ;

: LOOKAHEAD PARSE-NAME EVALUATE ;

: FORWARD LOOKAHEAD X +! ;
: DOWN    LOOKAHEAD Y +! ;
: UP      LOOKAHEAD Y -! ;

: PRINT-ANSWER X @ Y @ * . CR ;

INPUT INPUT-SIZE @ EVALUATE

PRINT-ANSWER QUIT
